POST http://localhost:3100/login
content-type: application/json

{
    "email":"tuvshinturbatzorig@gmail.com",
    "password":"12345678"
}


POST http://localhost:3100/signup
content-type: application/json

{
    "email":"tuvshinturbatzorig@gmail.com",
    "password":"12345678"
}

GET http://localhost:3100/posts?category=Posts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1OTQzMjk2MTAsImV4cCI6MTU5NDMzMzIxMH0.6Zv5ocL1JX-6D-Wyo5EHzTNzXfU8U2xysV5hwYUSqxQ